name: CI

on:
  pull_request:
    branches: [master]

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # env:
    #   VITE_API_BASE_URL: http://localhost:3000

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.13.0'
          cache: 'pnpm'

      - name: Cache Vitest
        uses: actions/cache@v4
        with:
          path: .vitest
          key: vitest-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Cache Playwright
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Commitlint
        run: |
          pnpm exec commitlint \
            --from=${{ github.event.pull_request.base.sha }} \
            --to=HEAD

      - name: Quality check (human)
        run: pnpm run ci
